// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/accounts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all active accounts belonging to the authenticated client",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "List client accounts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/banking-service_internal_dto.AccountSummaryResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new bank account for a client. Account kind must be \"Current\" or \"Foreign\". Current accounts require a subtype; foreign accounts require a currency code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Create a new bank account",
                "parameters": [
                    {
                        "description": "Account creation data",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/banking-service_internal_dto.CreateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/banking-service_internal_dto.AccountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/api/accounts/{accountNumber}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns full details for a specific account owned by the authenticated client",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Get account details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account number",
                        "name": "accountNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/banking-service_internal_dto.AccountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/api/accounts/{accountNumber}/limits": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Confirms a pending limit change request using the verification code from the mobile app",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Confirm account limit change",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account number",
                        "name": "accountNumber",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Verification code, you can use 1234 for testing but still needs request to be made first",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/banking-service_internal_dto.ConfirmLimitsChangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/api/accounts/{accountNumber}/limits/request": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Initiates a limit change request for an account. Sends a verification code for confirmation via mobile app, temporarily returned in body as code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Request account limit change",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account number",
                        "name": "accountNumber",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New daily and monthly limits",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/banking-service_internal_dto.RequestLimitsChangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/banking-service_internal_dto.RequestLimitsChangeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/api/accounts/{accountNumber}/name": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the display name of an account owned by the authenticated client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Update account name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account number",
                        "name": "accountNumber",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New account name",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/banking-service_internal_dto.UpdateAccountNameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/api/accounts/{accountNumber}/payments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of payments for an account, filterable by status, date range, and amount. Only the account owner can access this.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "List account payments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account number",
                        "name": "accountNumber",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by status (processing, completed, rejected)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter from date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum amount filter",
                        "name": "min_amount",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum amount filter",
                        "name": "max_amount",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/banking-service_internal_dto.ListPaymentsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Returns service health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "banking-service_internal_dto.AccountResponse": {
            "type": "object",
            "properties": {
                "account_kind": {
                    "type": "string"
                },
                "account_number": {
                    "type": "string"
                },
                "account_type": {
                    "type": "string"
                },
                "available_balance": {
                    "type": "number"
                },
                "balance": {
                    "type": "number"
                },
                "client_id": {
                    "type": "integer"
                },
                "company_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "$ref": "#/definitions/banking-service_internal_model.CurrencyCode"
                },
                "daily_limit": {
                    "type": "number"
                },
                "daily_spending": {
                    "type": "number"
                },
                "employee_id": {
                    "type": "integer"
                },
                "expires_at": {
                    "type": "string"
                },
                "maintenance_fee": {
                    "type": "number"
                },
                "monthly_limit": {
                    "type": "number"
                },
                "monthly_spending": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "reserved_funds": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "subtype": {
                    "type": "string"
                }
            }
        },
        "banking-service_internal_dto.AccountSummaryResponse": {
            "type": "object",
            "properties": {
                "account_kind": {
                    "type": "string"
                },
                "account_number": {
                    "type": "string"
                },
                "account_type": {
                    "type": "string"
                },
                "available_balance": {
                    "type": "number"
                },
                "balance": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "reserved_funds": {
                    "type": "number"
                }
            }
        },
        "banking-service_internal_dto.ConfirmLimitsChangeRequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "banking-service_internal_dto.CreateAccountRequest": {
            "type": "object",
            "required": [
                "account_kind",
                "account_type",
                "client_id",
                "employee_id",
                "expires_at",
                "name"
            ],
            "properties": {
                "account_kind": {
                    "$ref": "#/definitions/banking-service_internal_model.AccountKind"
                },
                "account_type": {
                    "$ref": "#/definitions/banking-service_internal_model.AccountType"
                },
                "client_id": {
                    "type": "integer"
                },
                "company_id": {
                    "type": "integer"
                },
                "create_card": {
                    "type": "boolean"
                },
                "currency_code": {
                    "description": "required if AccountKind=Foreign",
                    "allOf": [
                        {
                            "$ref": "#/definitions/banking-service_internal_model.CurrencyCode"
                        }
                    ]
                },
                "employee_id": {
                    "type": "integer"
                },
                "expires_at": {
                    "type": "string"
                },
                "initial_balance": {
                    "type": "number",
                    "minimum": 0
                },
                "name": {
                    "type": "string"
                },
                "subtype": {
                    "description": "required if AccountKind=Current",
                    "allOf": [
                        {
                            "$ref": "#/definitions/banking-service_internal_model.Subtype"
                        }
                    ]
                }
            }
        },
        "banking-service_internal_dto.ListPaymentsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/banking-service_internal_dto.PaymentSummaryResponse"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "banking-service_internal_dto.PaymentSummaryResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "payer_account": {
                    "type": "string"
                },
                "payment_code": {
                    "type": "string"
                },
                "purpose": {
                    "type": "string"
                },
                "recipient_account": {
                    "type": "string"
                },
                "recipient_name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "banking-service_internal_dto.RequestLimitsChangeRequest": {
            "type": "object",
            "required": [
                "daily_limit",
                "monthly_limit"
            ],
            "properties": {
                "daily_limit": {
                    "type": "number"
                },
                "monthly_limit": {
                    "type": "number"
                }
            }
        },
        "banking-service_internal_dto.RequestLimitsChangeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "banking-service_internal_dto.UpdateAccountNameRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "banking-service_internal_model.AccountKind": {
            "type": "string",
            "enum": [
                "Current",
                "Foreign"
            ],
            "x-enum-varnames": [
                "AccountKindCurrent",
                "AccountKindForeign"
            ]
        },
        "banking-service_internal_model.AccountType": {
            "type": "string",
            "enum": [
                "Personal",
                "Business"
            ],
            "x-enum-varnames": [
                "AccountTypePersonal",
                "AccountTypeBusiness"
            ]
        },
        "banking-service_internal_model.CurrencyCode": {
            "type": "string",
            "enum": [
                "EUR",
                "USD",
                "CHF",
                "GBP",
                "JPY",
                "CAD",
                "AUD",
                "RSD"
            ],
            "x-enum-varnames": [
                "EUR",
                "USD",
                "CHF",
                "GBP",
                "JPY",
                "CAD",
                "AUD",
                "RSD"
            ]
        },
        "banking-service_internal_model.Subtype": {
            "type": "string",
            "enum": [
                "Standard",
                "Savings",
                "Pension",
                "Youth",
                "Student",
                "Unemployed",
                "LLC",
                "JointStock",
                "Foundation"
            ],
            "x-enum-varnames": [
                "SubtypeStandard",
                "SubtypeSavings",
                "SubtypePension",
                "SubtypeYouth",
                "SubtypeStudent",
                "SubtypeUnemployed",
                "SubtypeLLC",
                "SubtypeJointStock",
                "SubtypeFoundation"
            ]
        },
        "errors.AppError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Authorization header using the Bearer scheme.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Banking Service API",
	Description:      "API for managing accounts, balances, and banking operations.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
