// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: common/proto/trading.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferFundsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromManagerId uint64                 `protobuf:"varint,1,opt,name=from_manager_id,json=fromManagerId,proto3" json:"from_manager_id,omitempty"`
	ToManagerId   uint64                 `protobuf:"varint,2,opt,name=to_manager_id,json=toManagerId,proto3" json:"to_manager_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferFundsRequest) Reset() {
	*x = TransferFundsRequest{}
	mi := &file_common_proto_trading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFundsRequest) ProtoMessage() {}

func (x *TransferFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_trading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFundsRequest.ProtoReflect.Descriptor instead.
func (*TransferFundsRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_trading_proto_rawDescGZIP(), []int{0}
}

func (x *TransferFundsRequest) GetFromManagerId() uint64 {
	if x != nil {
		return x.FromManagerId
	}
	return 0
}

func (x *TransferFundsRequest) GetToManagerId() uint64 {
	if x != nil {
		return x.ToManagerId
	}
	return 0
}

type TransferFundsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FundsTransferred uint64                 `protobuf:"varint,1,opt,name=funds_transferred,json=fundsTransferred,proto3" json:"funds_transferred,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransferFundsResponse) Reset() {
	*x = TransferFundsResponse{}
	mi := &file_common_proto_trading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferFundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFundsResponse) ProtoMessage() {}

func (x *TransferFundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_trading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFundsResponse.ProtoReflect.Descriptor instead.
func (*TransferFundsResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_trading_proto_rawDescGZIP(), []int{1}
}

func (x *TransferFundsResponse) GetFundsTransferred() uint64 {
	if x != nil {
		return x.FundsTransferred
	}
	return 0
}

var File_common_proto_trading_proto protoreflect.FileDescriptor

const file_common_proto_trading_proto_rawDesc = "" +
	"\n" +
	"\x1acommon/proto/trading.proto\x12\n" +
	"trading.v1\"b\n" +
	"\x14TransferFundsRequest\x12&\n" +
	"\x0ffrom_manager_id\x18\x01 \x01(\x04R\rfromManagerId\x12\"\n" +
	"\rto_manager_id\x18\x02 \x01(\x04R\vtoManagerId\"D\n" +
	"\x15TransferFundsResponse\x12+\n" +
	"\x11funds_transferred\x18\x01 \x01(\x04R\x10fundsTransferred2f\n" +
	"\x0eTradingService\x12T\n" +
	"\rTransferFunds\x12 .trading.v1.TransferFundsRequest\x1a!.trading.v1.TransferFundsResponseB\x12Z\x10common/pkg/pb;pbb\x06proto3"

var (
	file_common_proto_trading_proto_rawDescOnce sync.Once
	file_common_proto_trading_proto_rawDescData []byte
)

func file_common_proto_trading_proto_rawDescGZIP() []byte {
	file_common_proto_trading_proto_rawDescOnce.Do(func() {
		file_common_proto_trading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_trading_proto_rawDesc), len(file_common_proto_trading_proto_rawDesc)))
	})
	return file_common_proto_trading_proto_rawDescData
}

var file_common_proto_trading_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_trading_proto_goTypes = []any{
	(*TransferFundsRequest)(nil),  // 0: trading.v1.TransferFundsRequest
	(*TransferFundsResponse)(nil), // 1: trading.v1.TransferFundsResponse
}
var file_common_proto_trading_proto_depIdxs = []int32{
	0, // 0: trading.v1.TradingService.TransferFunds:input_type -> trading.v1.TransferFundsRequest
	1, // 1: trading.v1.TradingService.TransferFunds:output_type -> trading.v1.TransferFundsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_trading_proto_init() }
func file_common_proto_trading_proto_init() {
	if File_common_proto_trading_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_trading_proto_rawDesc), len(file_common_proto_trading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_trading_proto_goTypes,
		DependencyIndexes: file_common_proto_trading_proto_depIdxs,
		MessageInfos:      file_common_proto_trading_proto_msgTypes,
	}.Build()
	File_common_proto_trading_proto = out.File
	file_common_proto_trading_proto_goTypes = nil
	file_common_proto_trading_proto_depIdxs = nil
}
